# Generated by Django 5.0.2 on 2024-03-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lostdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostdata',
            name='rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rented'),
        ),
    ]
