# Generated by Django 5.0.2 on 2024-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bag_author_remove_bag_bookname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
