# Generated by Django 5.0.2 on 2024-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='price',
        ),
        migrations.AddField(
            model_name='rented',
            name='finestatus',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
