# Generated by Django 5.0.2 on 2024-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_rented_author_remove_rented_bookname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostdata',
            name='rent',
        ),
        migrations.AddField(
            model_name='lostdata',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
