# Generated by Django 5.0.2 on 2024-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_lostdata_rent_lostdata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostdata',
            name='fine',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
