# Generated by Django 5.0.2 on 2024-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lostdata_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publisherid',
            field=models.TextField(null=True),
        ),
    ]
