# Generated by Django 5.0.2 on 2024-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rented_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='rdate',
            field=models.DateField(null=True),
        ),
    ]
