# Generated by Django 5.0.2 on 2024-03-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rented_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostdata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
